title: wandering-isle
email: kaeberlein.c@northeastern.edu
description: Website of Asteria Kaeberlein
github_username:  wandering-isle
url: https://wandering-isle.github.io
# Build settings
gems:
  - jekyll-seo-tag
